version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres16-soundbridge
    environment:
      POSTGRES_DB: soundbridge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql # DB 초기화 스크립트
    networks:
      - soundbridge
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soundbridge-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - soundbridge
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
#    entrypoint: ["sh", "docker/app/entrypoint.sh"]
volumes:
  db_data:

networks:
  soundbridge: 
